version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: revops-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add PostgreSQL for more robust data storage
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: revops-postgres
  #   environment:
  #     POSTGRES_DB: revops
  #     POSTGRES_USER: revops_user
  #     POSTGRES_PASSWORD: revops_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  redis_data:
  # postgres_data:
